sudo: required
language: node_js
node_js:
  - node # latest stable node build
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
before_script:
  - find test -type d -exec chmod g+s {} \;
  - sudo chown root test/fixtures/not-owned/not-owned.txt
  - sudo chmod 666 test/fixtures/not-owned/not-owned.txt
script:
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then npm run lint; fi;
  - npm test
after_script:
  - npm run coveralls
