# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/lang/nodejs-iojs

environment:
  matrix:
    # node.js
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - ps: if ($env:nodejs_version -eq '8') { npm run lint }

test_script:
  - node --version
  - npm --version
  - cmd: npm test

build: off

# build version format
version: "{build}"
